"""
classifier.py — Multi-signal AI content detection pipeline for Provenance Guard

Two required signals:
  1. LLM-as-judge  (Groq / llama-3.3-70b-versatile)
     Captures high-level semantic patterns: unnatural topic coherence,
     generic phrasing, lack of personal voice, overuse of hedging language.
  2. Stylometric heuristics (pure Python, no external libs)
     Captures statistical surface features: sentence-length variance,
     type-token ratio (vocabulary diversity), average word length,
     punctuation asymmetry, and paragraph structure regularity.

Stretch (ensemble) adds a third signal:
  3. Pseudo-perplexity proxy
     Estimates how predictable each word choice is relative to its
     local context — AI text tends to be more "on the curve" than
     human text, which introduces unexpected word choices.

Each signal returns a float in [0, 1] where:
  1.0  = definitely AI-generated
  0.0  = definitely human-written
"""

import re
import math
import statistics
from typing import TypedDict

from groq import Groq
from config import (
    GROQ_API_KEY, LLM_MODEL,
    SIGNAL_WEIGHT_LLM, SIGNAL_WEIGHT_STYLOMETRIC,
    SIGNAL_WEIGHT_LLM_ENSEMBLE, SIGNAL_WEIGHT_STYLOMETRIC_ENSEMBLE,
    SIGNAL_WEIGHT_PERPLEXITY_ENSEMBLE,
)

_client = Groq(api_key=GROQ_API_KEY)


# ── Type alias ─────────────────────────────────────────────────────────────

class SignalResult(TypedDict):
    score: float          # [0, 1] — higher = more AI-like
    label: str            # "ai" | "human" | "uncertain"
    explanation: str      # brief human-readable rationale


class DetectionResult(TypedDict):
    final_score: float    # weighted combination of all signals
    signals: dict         # signal_name → SignalResult
    weights: dict         # signal_name → float weight used


# ── Signal 1 — LLM-as-judge ───────────────────────────────────────────────

_LLM_SYSTEM_PROMPT = """You are an expert forensic linguist tasked with determining whether a piece of creative writing was authored by a human or generated by an AI language model.

You will evaluate the text across four dimensions:
1. VOICE — Does the text have a distinctive, idiosyncratic personal voice, or is it generic and smooth?
2. STRUCTURE — Is the structure organic and unpredictable, or formulaic and template-like?
3. SEMANTIC COHERENCE — Does the text make unexpected but meaningful leaps, or does it stay safely "on topic" in a way that feels optimized?
4. LINGUISTIC FINGERPRINT — Are there unusual word choices, syntax quirks, or deliberate "mistakes" that signal a human author?

AI-generated text often exhibits: consistent paragraph length, hedge phrases ("it's worth noting"), over-explained transitions, absence of genuinely surprising metaphors, and a kind of surface-level polish that lacks depth.

Human text often exhibits: inconsistent flow, sudden tonal shifts, personal references, unconventional punctuation for emphasis, and moments of raw or rough expression.

Respond in EXACTLY this format — no other text:
SCORE: <float between 0.00 and 1.00 where 1.00=definitely AI, 0.00=definitely human>
LABEL: <ai|human|uncertain>
EXPLANATION: <one sentence, under 80 words>"""


def signal_llm(content: str) -> SignalResult:
    """
    Use the LLM as a judge to score content for AI authorship.
    Returns a SignalResult with score in [0, 1].
    """
    try:
        response = _client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": _LLM_SYSTEM_PROMPT},
                {"role": "user", "content": f"Evaluate the following content:\n\n---\n{content[:4000]}\n---"},
            ],
            temperature=0.1,   # low temp for consistent evaluation
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()
        return _parse_llm_response(raw)
    except Exception as exc:
        # Fail to uncertain rather than crashing the pipeline
        return SignalResult(
            score=0.5,
            label="uncertain",
            explanation=f"LLM signal unavailable: {str(exc)[:80]}",
        )


def _parse_llm_response(raw: str) -> SignalResult:
    """Parse the structured LLM response into a SignalResult."""
    score = 0.5
    label = "uncertain"
    explanation = "Could not parse LLM response."

    score_match = re.search(r"SCORE:\s*([0-9.]+)", raw, re.IGNORECASE)
    label_match = re.search(r"LABEL:\s*(ai|human|uncertain)", raw, re.IGNORECASE)
    expl_match = re.search(r"EXPLANATION:\s*(.+)", raw, re.IGNORECASE | re.DOTALL)

    if score_match:
        try:
            score = max(0.0, min(1.0, float(score_match.group(1))))
        except ValueError:
            pass

    if label_match:
        label = label_match.group(1).lower()

    if expl_match:
        explanation = expl_match.group(1).strip()[:200]

    # Consistency check: snap label to match score if they disagree badly
    if score >= 0.75 and label == "human":
        label = "uncertain"
    if score <= 0.25 and label == "ai":
        label = "uncertain"

    return SignalResult(score=score, label=label, explanation=explanation)


# ── Signal 2 — Stylometric heuristics ─────────────────────────────────────
#
# The following features correlate with AI vs. human authorship based on
# published research on stylometric attribution:
#
#   • Sentence-length standard deviation (SD)
#       Human writers vary sentence length more wildly (high SD).
#       AI text tends toward consistent, medium-length sentences (low SD).
#
#   • Type-Token Ratio (TTR) — unique words / total words
#       Human writers reuse words more naturalistically, often repeating
#       for effect or rhythm. AI can be artificially diverse or artificially
#       repetitive depending on the task. We weight both extremes as signals.
#
#   • Average word length
#       AI prose tends toward slightly longer, more "formal" word choices
#       on average, even in creative contexts.
#
#   • Paragraph regularity (length variance across paragraphs)
#       AI text tends toward uniform paragraph lengths. Human text is
#       more structurally jagged.
#
#   • Exclamation-to-question ratio
#       Human creative writing uses exclamations and rhetorical questions
#       more organically. AI tends to avoid them or use them formulaically.

def signal_stylometric(content: str) -> SignalResult:
    """
    Pure-Python stylometric analysis. No external libraries.
    Returns a SignalResult with score in [0, 1] (1 = AI-like).
    """
    features = _extract_stylometric_features(content)
    score = _score_stylometric_features(features)
    label = _score_to_label(score)

    feature_summary = (
        f"sent_len_sd={features['sent_len_sd']:.1f}, "
        f"ttr={features['ttr']:.2f}, "
        f"avg_word_len={features['avg_word_len']:.2f}, "
        f"para_sd={features['para_len_sd']:.1f}"
    )
    explanation = f"Stylometric analysis: {feature_summary}. Score={score:.2f}."
    return SignalResult(score=score, label=label, explanation=explanation)


def _tokenize_sentences(text: str) -> list[str]:
    """Simple sentence splitter that handles common punctuation."""
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    return [s for s in sentences if s.strip()]


def _tokenize_words(text: str) -> list[str]:
    return re.findall(r"[a-zA-Z']+", text.lower())


def _extract_stylometric_features(content: str) -> dict:
    sentences = _tokenize_sentences(content)
    words = _tokenize_words(content)
    paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]

    # Sentence length (in words)
    sent_lengths = [len(_tokenize_words(s)) for s in sentences if _tokenize_words(s)]
    sent_len_mean = statistics.mean(sent_lengths) if sent_lengths else 0.0
    sent_len_sd = statistics.stdev(sent_lengths) if len(sent_lengths) > 1 else 0.0

    # Type-Token Ratio
    total_words = len(words)
    unique_words = len(set(words))
    ttr = unique_words / total_words if total_words > 0 else 0.0

    # Average word length
    avg_word_len = (
        sum(len(w) for w in words) / len(words) if words else 0.0
    )

    # Paragraph length variance (in sentences per paragraph)
    para_sentence_counts = []
    for para in paragraphs:
        para_sents = _tokenize_sentences(para)
        if para_sents:
            para_sentence_counts.append(len(para_sents))
    para_len_sd = (
        statistics.stdev(para_sentence_counts)
        if len(para_sentence_counts) > 1
        else 0.0
    )

    # Punctuation signals
    exclamations = content.count("!")
    questions = content.count("?")
    total_puncts = exclamations + questions
    excl_ratio = exclamations / total_puncts if total_puncts > 0 else 0.5

    # Hedge phrase density (common AI hedges per 100 words)
    hedge_phrases = [
        "it's worth noting", "it is worth noting", "it's important to",
        "it is important to", "in conclusion", "in summary", "to summarize",
        "furthermore", "moreover", "in addition", "on the other hand",
        "having said that", "that being said", "needless to say",
        "at the end of the day", "it goes without saying",
    ]
    content_lower = content.lower()
    hedge_count = sum(content_lower.count(phrase) for phrase in hedge_phrases)
    hedge_density = (hedge_count / total_words * 100) if total_words > 0 else 0.0

    return {
        "sent_len_mean": sent_len_mean,
        "sent_len_sd": sent_len_sd,
        "ttr": ttr,
        "avg_word_len": avg_word_len,
        "para_len_sd": para_len_sd,
        "excl_ratio": excl_ratio,
        "hedge_density": hedge_density,
        "total_words": total_words,
        "num_sentences": len(sent_lengths),
    }


def _score_stylometric_features(f: dict) -> float:
    """
    Convert extracted features into a single [0, 1] AI-likelihood score.

    Each sub-score is in [0, 1]; they are averaged with equal weight.
    Thresholds are tuned based on typical patterns in AI vs. human creative text.
    """
    sub_scores: list[float] = []

    # 1. Low sentence-length SD → more AI-like
    #    Human creative text: SD typically 5–15 words
    #    AI creative text: SD typically 2–7 words
    sd = f["sent_len_sd"]
    if sd < 2:
        sub_scores.append(0.85)
    elif sd < 5:
        sub_scores.append(0.65)
    elif sd < 10:
        sub_scores.append(0.35)
    else:
        sub_scores.append(0.15)

    # 2. TTR: very high (>0.85) or very low (<0.40) — both can signal AI
    #    Humans cluster around 0.50–0.75 in creative prose
    #    NOTE: short texts (< 150 words) naturally have inflated TTR regardless
    #    of authorship — skip this feature for short inputs to avoid noise.
    ttr = f["ttr"]
    total_words = f.get("total_words", 0)
    if total_words < 150:
        sub_scores.append(0.50)   # not enough words to interpret TTR reliably
    elif ttr > 0.85 or ttr < 0.35:
        sub_scores.append(0.70)
    elif 0.50 <= ttr <= 0.75:
        sub_scores.append(0.25)
    else:
        sub_scores.append(0.50)

    # 3. Average word length: AI prose skews toward 4.8–5.5 chars
    awl = f["avg_word_len"]
    if 4.8 <= awl <= 5.5:
        sub_scores.append(0.60)
    elif awl > 5.5:
        sub_scores.append(0.70)  # very long words — likely academic-AI style
    else:
        sub_scores.append(0.30)

    # 4. Low paragraph length variance → AI-like
    para_sd = f["para_len_sd"]
    if f.get("total_words", 0) < 100:
        # Not enough text to evaluate paragraph structure reliably
        sub_scores.append(0.50)
    elif para_sd < 0.5:
        sub_scores.append(0.75)
    elif para_sd < 1.5:
        sub_scores.append(0.50)
    else:
        sub_scores.append(0.25)

    # 5. High hedge phrase density → AI-like
    hedge = f["hedge_density"]
    if hedge > 1.5:
        sub_scores.append(0.85)
    elif hedge > 0.5:
        sub_scores.append(0.60)
    else:
        sub_scores.append(0.30)

    return round(statistics.mean(sub_scores), 4)


# ── Signal 3 — Pseudo-perplexity proxy (stretch) ──────────────────────────

def signal_perplexity_proxy(content: str) -> SignalResult:
    """
    Estimate text predictability using a simple bigram-based proxy.
    AI text tends to have lower "surprisal" — word choices are safer and
    more expected given the local context.

    This is a lightweight approximation, not true perplexity, but it
    captures a meaningful dimension independent of the other two signals.
    """
    words = _tokenize_words(content)
    if len(words) < 20:
        return SignalResult(
            score=0.5, label="uncertain",
            explanation="Too short for perplexity analysis."
        )

    # Build a simple bigram model from the content itself
    # (self-referential, but still meaningful for regularity detection)
    bigrams: dict[tuple, list[str]] = {}
    for i in range(len(words) - 1):
        key = (words[i],)
        bigrams.setdefault(key, []).append(words[i + 1])

    # Compute average branching factor: how many distinct next words
    # follow each word. Low branching → more predictable → more AI-like.
    branching_factors = [len(set(v)) for v in bigrams.values() if len(v) >= 2]
    if not branching_factors:
        return SignalResult(
            score=0.5, label="uncertain",
            explanation="Insufficient data for perplexity proxy."
        )

    avg_branching = statistics.mean(branching_factors)

    # Also count "safe vocabulary" — common function words as a fraction of all words
    safe_words = {
        "the", "a", "an", "is", "are", "was", "were", "be", "been",
        "have", "has", "had", "do", "does", "did", "will", "would",
        "could", "should", "may", "might", "must", "and", "but", "or",
        "in", "on", "at", "to", "of", "for", "with", "by", "from",
        "this", "that", "these", "those", "it", "its",
    }
    safe_ratio = sum(1 for w in words if w in safe_words) / len(words)

    # Score: low branching + high safe-word ratio → more AI-like
    branching_score = max(0.0, min(1.0, 1.0 - (avg_branching - 1.0) / 5.0))
    safe_score = max(0.0, min(1.0, safe_ratio / 0.5))  # 0.5 safe ratio = fully AI-like
    score = round((branching_score * 0.6 + safe_score * 0.4), 4)

    label = _score_to_label(score)
    explanation = (
        f"Perplexity proxy: avg_branching={avg_branching:.2f}, "
        f"safe_word_ratio={safe_ratio:.2f}. Score={score:.2f}."
    )
    return SignalResult(score=score, label=label, explanation=explanation)


# ── Helper ─────────────────────────────────────────────────────────────────

def _score_to_label(score: float) -> str:
    if score >= 0.70:
        return "ai"
    if score <= 0.35:
        return "human"
    return "uncertain"


# ── Main pipeline ──────────────────────────────────────────────────────────

def run_detection_pipeline(content: str, ensemble: bool = False) -> DetectionResult:
    """
    Run the full multi-signal detection pipeline.

    Args:
        content: The text to classify.
        ensemble: If True, run the 3-signal ensemble (stretch feature).

    Returns:
        DetectionResult with final_score, per-signal results, and weights used.
    """
    llm_result = signal_llm(content)
    stylo_result = signal_stylometric(content)

    if ensemble:
        perp_result = signal_perplexity_proxy(content)
        weights = {
            "llm": SIGNAL_WEIGHT_LLM_ENSEMBLE,
            "stylometric": SIGNAL_WEIGHT_STYLOMETRIC_ENSEMBLE,
            "perplexity_proxy": SIGNAL_WEIGHT_PERPLEXITY_ENSEMBLE,
        }
        final_score = (
            llm_result["score"] * weights["llm"]
            + stylo_result["score"] * weights["stylometric"]
            + perp_result["score"] * weights["perplexity_proxy"]
        )
        signals = {
            "llm": llm_result,
            "stylometric": stylo_result,
            "perplexity_proxy": perp_result,
        }
    else:
        weights = {
            "llm": SIGNAL_WEIGHT_LLM,
            "stylometric": SIGNAL_WEIGHT_STYLOMETRIC,
        }
        final_score = (
            llm_result["score"] * weights["llm"]
            + stylo_result["score"] * weights["stylometric"]
        )
        signals = {
            "llm": llm_result,
            "stylometric": stylo_result,
        }

    final_score = round(max(0.0, min(1.0, final_score)), 4)

    return DetectionResult(
        final_score=final_score,
        signals=signals,
        weights=weights,
    )
