"""
confidence.py — Confidence scoring and transparency label generation

Design philosophy
─────────────────
The raw detection score from the pipeline is a number in [0, 1] where
1.0 = maximally AI-like. But we must not treat this as a binary decision.

A platform showing content to readers has an asymmetric error cost:
  • False positive (labeling a human's work as AI) → harms a real creator's
    reputation, destroys trust in the platform, and may violate their rights.
  • False negative (missing AI content) → slightly misleads readers but causes
    no immediate harm to an individual creator.

This asymmetry means:
  1. We bias toward "uncertain" rather than forcing a confident verdict.
  2. High-confidence AI labels require a score well above 0.5 (>= 0.75).
  3. High-confidence human labels also require a score well below 0.5 (<= 0.25).
  4. The uncertain zone (0.25–0.75) deliberately produces a neutral label.

Label variants
──────────────
See `build_transparency_label()` for the exact text of all three variants.
"""

from dataclasses import dataclass
from config import HIGH_CONFIDENCE_THRESHOLD, LOW_CONFIDENCE_THRESHOLD


@dataclass
class ConfidenceResult:
    verdict: str            # "ai" | "human" | "uncertain"
    confidence_score: float  # 0.0–1.0 — probability-like measure of certainty
    raw_score: float        # raw pipeline score (0=human, 1=AI)
    label: dict             # transparency label dict (see build_transparency_label)


# ── Human-readable confidence → percentage ────────────────────────────────

def _confidence_pct(score: float, verdict: str) -> int:
    """
    Convert the raw pipeline score to a reader-meaningful confidence percentage.

    For AI verdicts: confidence rises as score approaches 1.0.
    For human verdicts: confidence rises as score approaches 0.0.
    For uncertain: percentage reflects how far the score is from 0.5.
    """
    if verdict == "ai":
        # Map [0.75, 1.0] → [50%, 99%]
        return min(99, int(50 + (score - 0.75) / 0.25 * 49))
    elif verdict == "human":
        # Map [0.0, 0.25] → [99%, 50%]
        return min(99, int(99 - score / 0.25 * 49))
    else:
        # Uncertain: show how far from 50/50 we are (capped at 49%)
        distance_from_center = abs(score - 0.5)
        return min(49, int(distance_from_center / 0.25 * 49))


def score_to_verdict(raw_score: float) -> str:
    """
    Map a raw pipeline score to a categorical verdict.

    Thresholds are intentionally asymmetric — see module docstring.
    The uncertain band is wide (0.25–0.75) to protect creators from
    false positives.
    """
    if raw_score >= HIGH_CONFIDENCE_THRESHOLD:
        return "ai"
    elif raw_score <= LOW_CONFIDENCE_THRESHOLD - 0.30:  # i.e., <= 0.25
        return "human"
    else:
        return "uncertain"


def compute_confidence(raw_score: float) -> float:
    """
    Convert the raw pipeline score into a symmetric confidence measure in [0, 1].

    0.5 = maximum uncertainty (score exactly at 0.5)
    1.0 = maximum confidence (score at 0.0 or 1.0)

    This lets callers easily check: confidence >= 0.75 means "high confidence"
    regardless of direction.
    """
    return round(abs(raw_score - 0.5) * 2, 4)


# ── Transparency label ─────────────────────────────────────────────────────

def build_transparency_label(verdict: str, raw_score: float) -> dict:
    """
    Build the full transparency label shown to platform readers.

    Returns a dict with:
      - heading:      bold title line
      - body:         1-2 sentence plain-language explanation
      - badge:        short badge text (e.g. for UI chips)
      - icon:         emoji visual cue
      - detail:       optional technical detail for interested readers
      - appeal_note:  always present — tells creators how to appeal
    """
    pct = _confidence_pct(raw_score, verdict)
    score_display = f"{raw_score:.0%}"

    if verdict == "ai":
        # ── HIGH-CONFIDENCE AI LABEL ──────────────────────────────────────
        return {
            "heading": "⚠️ Likely AI-Generated",
            "badge": "AI-GENERATED",
            "icon": "🤖",
            "body": (
                f"Our system found strong signals suggesting this content was "
                f"generated by an AI tool rather than written by a human author. "
                f"Confidence: {pct}%."
            ),
            "detail": (
                "This determination is based on a combination of language-pattern "
                "analysis and stylometric features. It is not infallible."
            ),
            "appeal_note": (
                "If you are the creator and believe this is incorrect, "
                "you can submit an appeal to have your content reviewed by a human moderator."
            ),
        }

    elif verdict == "human":
        # ── HIGH-CONFIDENCE HUMAN LABEL ───────────────────────────────────
        return {
            "heading": "✅ Likely Human-Written",
            "badge": "HUMAN-WRITTEN",
            "icon": "✍️",
            "body": (
                f"Our system found strong signals suggesting this content was "
                f"written by a human author. "
                f"Confidence: {pct}%."
            ),
            "detail": (
                "This determination is based on a combination of language-pattern "
                "analysis and stylometric features. No automated system is perfect."
            ),
            "appeal_note": (
                "Attribution labels can be appealed if you believe the result is inaccurate."
            ),
        }

    else:
        # ── UNCERTAIN LABEL ────────────────────────────────────────────────
        return {
            "heading": "🔍 Authorship Unclear",
            "badge": "UNVERIFIED",
            "icon": "❓",
            "body": (
                "Our system could not determine with confidence whether this content "
                "was written by a human or generated by AI. "
                "The signals we measure gave mixed or inconclusive results."
            ),
            "detail": (
                f"Detection score: {score_display}. A score near 50% means our "
                "signals did not strongly point in either direction."
            ),
            "appeal_note": (
                "Creators can submit additional context or request human review "
                "to clarify the attribution of this content."
            ),
        }


# ── Public entry point ─────────────────────────────────────────────────────

def evaluate(raw_score: float) -> ConfidenceResult:
    """
    Given a raw pipeline score, return the full ConfidenceResult including
    the transparency label.
    """
    verdict = score_to_verdict(raw_score)
    confidence = compute_confidence(raw_score)
    label = build_transparency_label(verdict, raw_score)

    return ConfidenceResult(
        verdict=verdict,
        confidence_score=confidence,
        raw_score=raw_score,
        label=label,
    )
